#!/usr/bin/env bash

# configure mkinitcpio
sed -i '/^HOOKS/s/\(block \)\(.*filesystems\)/\1encrypt lvm2 \2/' /etc/mkinitcpio.conf

# generate initramfs for linux and linux-lts
mkinitcpio -p linux
mkinitcpio -p linux-lts